name: Build and Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile your_script_name.py  # Replace with your main script
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exydata-cli-${{ matrix.os }}
          path: dist/your_script_name*  # Adjust if needed

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: exydata-cli-*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
