name: Build and Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            ext: ""
          - os: macos-latest
            platform: mac
            ext: ""
          - os: windows-latest
            platform: windows
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Build binary
        run: go build -o ./dist/exydata-cli-${{ matrix.platform }}-${{ github.sha }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exydata-cli-${{ matrix.platform }}-${{ github.sha }}
          path: ./dist/exydata-cli-${{ matrix.platform }}-${{ github.sha }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: exydata-cli-*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
