name: Build and Publish Binaries
on:
  push:
    branches:
      - main

jobs:
  build-linux-macos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace 'x' with the desired Python version (e.g., 3.7, 3.8, etc.)

      - name: Install pyinstaller
        run: python -m pip install pyinstaller

      - name: Build Linux Binary
        run: |
          cd linux
          pip install -r requirements.txt
          pyinstaller --onefile voltmetrix.py

      - name: Archive Binaries (Linux and macOS)
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            linux/dist/voltmetrix
